global:
  scrape_interval: 15s

scrape_configs:
  - job_name: rust-api
    metrics_path: /metrics
    static_configs:
      - targets: ['rust-api:21081']
  - job_name: postgres
    static_configs:
      - targets: ['postgres_exporter:9187']
  - job_name: redis
    static_configs:
      - targets: ['redis_exporter:9121']
  - job_name: pushgateway
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091']
