server {
    listen 21080;
    server_name localhost;
    include /etc/nginx/conf.d/_locations.inc;
}
server {
    listen 21443 ssl;
    server_name localhost;
    ssl_certificate     /etc/nginx/certs/fullchain.pem;
    ssl_certificate_key /etc/nginx/certs/privkey.pem;
    include /etc/nginx/conf.d/_locations.inc;
}
